version: '3.8'

networks:
  erp_network:
    driver: bridge

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./PERSONAL-FINANCE-API:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql
    networks:
      - erp_network

  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "password"
    ports:
      - 3306:1433
    networks:
      - erp_network

    